# Docker compose to run multiple influxdb instances on one machine
version: '3'
services:
  influxdb:
    container_name: influxdb
    #restart: always
    #network_mode: host
    image: influxdb:1.8
    volumes:
      - ./influxdb-docker.conf:/etc/influxdb/influxdb.conf:ro
      - /var/lib/influxdb/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"

  grafana:
    # restart: always
    image: grafana/grafana:9.0.3
    # network_mode: host
    ports:
      - "3000:3000"
    volumes:
      - /var/lib/grafana:/var/lib/grafana
    user: "0"
    depends_on:
      - influxdb
    environment:
      - GF_INSTALL_PLUGINS=https://github.com/cloudspout/cloudspout-button-panel/releases/download/7.0.23/cloudspout-button-panel.zip;cloudspout-button-panel
